In [70]:
import pandas as pd

df = pd.read_json("Office_Products_5.json", lines=True)

In [71]:
df.head()

       reviewerID        asin         reviewerName helpful  \
0  A32T2H8150OJLU  B00000JBLH                  ARH  [3, 4]
1  A3MAFS04ZABRGO  B00000JBLH     Let it Be "Alan"  [7, 9]
2  A1F1A0QQP2XVH5  B00000JBLH               Mark B  [3, 3]
3   A49R5DBXXQDE5  B00000JBLH         R. D Johnson  [7, 8]
4  A2XRMQA6PJ5ZJ8  B00000JBLH  Roger J. Buffington  [0, 0]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reviewText  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling.  I searched for another one to replace it, but found one difficult to come by in my area.  So, I decided to buy up and purchased an HP 49G.  What a mistake!  I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best.  The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you.  It's programmable.  It does basic statistics well, and many business applications too.  The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend.  I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!
1  WHY THIS BELATED REVIEW? I feel very obliged to share my views about this old workhorse, the HP12C GOLD at its 25th anniversary and my 1Oth year as a satisfied ower user and fan. Especially after sharing my frank views on Amazon about two of its three successors on Amazon.com, burying the HP12c Platinum (2004 1st release, HP12cP) and praising the HP12c Platiunum Anniversary Edition (2006 3rd release, HP12cPAE or HP12cPA).To the majority of HP 12c calculator owners and fans, including the non-techkie nerd like myself, the name Hewlett-Packard To the majority of HP 12c calculator owners and fans. The brandname of Hewlett-Packard is synonymous with the highest quality and best range offered in handheld electronic business financial calculators before the first generation of personal computers hits the desktops of business users.To date (December 2007), the bearer of this "gold" standard is none other than the HP12C HP's "golden boy" in its calculator business segment.The HP12C now a matured product, is the only continuing HP handheld surviving calculator product since '81 and probably the longest selling electronic calculator ever. According to HP almost 15 million HP 12Cs, cPs was sold since ,it is probably the best selling HP (and RPN) calculator ever.As a proven product, the HP12C "gold" works from day 1, with its form factor and sofware remaining unchanged and has not been dethroned by rivals and even its HP successors which had come and go.Even with PC software versions being sold, the 12C remains the truly indispensable "portable" finance-business heldheld computer for its owners, professionals and students alike. This handy companion powers up immediately and is faster than any portable personal computers to jump right into the action.The HP12C is a serious product and the ultimate time tested solution, field tested proven by its users and survived all its rival products, the workhorse moves on.Anyone in charge of this HP line should always bear in mind that the continued production run of the HP 12c is a testimony of HP's quality and standard expected by its customers.Don't just listen to a HP12C fan here, I own and am using three out of 4 models of the HP 12C series, and it is amusing and somewhat disappointing to observe that it had taken HP at least four years and two major upgrades of the HP 12c Platinium, in its futile attempt to "fix & retire" the HP12C with three successors in the form of HP12cPlatinum since 2004.It would seems especially frustrating on the part of HP, to realize after all the effort spent on remaking the HP12cPlatinum models that it would not outdone its siblings the HP10bII and HP17bII+ series to seriously challenge the HP12C Gold.  However, by their own rights the HP10Bs and HP17Bs, and the HP12cPlatinum may find their rightful place in the HP financial calculator line, differentiating the HP12C GOLD in terms of price and functions.IMHO, this had happened because the following golden rules were infringed by HP...GOLDEN RULE I - A PRODUCT WHICH STILL SELLS ITSELF IS NEVER OBSOLETE.GOLDEN RULE II - IF IT AREN'T BROKEN, DON't FIX IT ! "The gold rule of thumb should always be guarded as gospel by the HP heldheld calculator product team. Based on the same reasoning, the HP12C's built quality and product standard is paramount to its users.GOLDEN RULE III - ALWAYS LISTEN TO YOUR CUSTOMERS! If in doubt, see rules I & II.GOLDEN RULE IV - ONLY OUTSOURCE THE MANUFACTURING OF YOUR PRODUCT TO SOMEONE WHO COULD BETTER YOUR OWN PRODUCT QUALITY. If in doubt ask IBM about Lenovo.GOLDEN RULE V - THE BENCHMARKING INDUSTRY STANDARD FOR THIS PRODUCT LINE IS THE HP12C. Just in case, if HP does not know or is not listening to its customers.GOLDEN RULE VI - DO NOT DISCONTINUE THE ICONIC HP12C GOLD. HP needs no reminder that the customer is always right. Please let your customer, the ultimate market force decide if the HP12C should ever be retired.As an ardent fan of HP12C and line of financial business & scientific calculators, I am of the view that the day when HP discontinue the HP12C would be the day it exit this business segment. I speculate this would happen when the HP brandname disappears from the 12C just like after IBM name had disappeared from ThinkPads and ThinkCentres.Since the price of GOLD is on the rise, it is indeed puzzling to fans of the HP12C, why HP did not release a genuine HP12C gold 25th anniversary model for the fans to mark the occasion, if replacing the discontinuing the HP12C GOLD is the intention READ ALL GOLDEN RULES above.To be fair, the silver HP12c Platinum Anniversary is very nice and has spotted the "retro" silver look of the HP 11C, however, it is still not the GOLD standard. With HP missing this golden opportunity to mark the occasion, I would love to see and own a HP 12C engraved with 50th Anniversary logo, reckon that this would be the ultimate testimony for the HP12C and a milestone for its fans.Looking forward, a GOLD 50th anniversary HP12C Anniversary model would be very nice for the fans.For HP, this is a lucrative business proposition. By now, they would have realized that if they have any of its products which could hit a 50th year home run  in 2031, it would not be from its other product line-it would be this original HP12C GOLD standard bearer. So please treat the old workhorse with the upmost respect!

In [72]:
df.dtypes

reviewerID        object
asin              object
reviewerName      object
helpful           object
reviewText        object
overall            int64
summary           object
unixReviewTime     int64
reviewTime        object
dtype: object

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53258 entries, 0 to 53257
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      53258 non-null  object
 1   asin            53258 non-null  object
 2   reviewerName    52799 non-null  object
 3   helpful         53258 non-null  object
 4   reviewText      53258 non-null  object
 5   overall         53258 non-null  int64
 6   summary         53258 non-null  object
 7   unixReviewTime  53258 non-null  int64
 8   reviewTime      53258 non-null  object
dtypes: int64(2), object(7)
memory usage: 3.7+ MB

In [74]:
review_counts = df['reviewerID'].value_counts()          # most active first (default)
review_counts = df['reviewerID'].value_counts().sort_values(ascending=False)  # least active first

In [75]:
review_counts

reviewerID
A3OXHLG6DIBRW8    94
A22I55P15NSAOX    81
A1Z16630QMH8Q6    77
A1ODOGXEYECQQ8    76
A22CW0ZHY3NJH8    76
                  ..
A1486KL0IOM7VM     5
AOE0XMITAJWDT      5
AA8M6331NI1EN      5
A49R5DBXXQDE5      5
A3MAFS04ZABRGO     5
Name: count, Length: 4905, dtype: int64

In [76]:
df[df['reviewerID']=='A3OXHLG6DIBRW8']

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
838,A3OXHLG6DIBRW8,B00004Z6NA,"C. Hill ""CFH""","[0, 0]","The Epson High-Gloss Premium Photo Paper is very high quality inkjet paper that produces fantastic looking, smudge resistant prints from myEpson Stylus Photo 2200 Inkjet Printer.This paper is very quick drying so prints can be stacked without worrying that they will stick together. I also like that it is fairly heavy stock so prints have the feel of professional lab quality.Highly Recommended!CFH",5,"High Quality, Quick Drying Photo Paper - Highly Recommended",1254614400,"10 4, 2009"
881,A3OXHLG6DIBRW8,B000050FZP,"C. Hill ""CFH""","[3, 3]","The AT&T; Trimeline is a very basic corded phone that works when the power goes out. We bought three of these (one for our house, shop, and my mother's house) to use mostly as backup for when our various cordless phones become unusable in during power outages (more frequent than I like in our area).We have these connected to line splitters (likeBelkin RJ11 Plug/2-RJ11 Jack Modular T Adapter) and they work just fine. These also have physical switches to adjust the ringer volume and phone volume which, although limited, does give us some control. It is also handy that the keypad is ""backlit"" and draws power directly from the phone line, allowing you to see the numbers in the dark.While these phones do have the ability to store numbers and even speed-dial, we have not set them up to do it.Highly Recommended!CFH",5,Handy For When The Power Goes Out - Highly Recommended,1284768000,"09 18, 2010"
1060,A3OXHLG6DIBRW8,B00005C3YY,"C. Hill ""CFH""","[7, 10]","This Matte Finish ""Magic"" Tape is so much better than the generic types for most uses. It goes on totally clear on most paper, it is very strong, and the matte finish doesn't easily reflect light so it doesn't draw attention to itself.The brand name ""Scotch"" has become a ""proprietary eponym"" for this type of clear tape, along the same lines as Band-Aid, Kleenex, and Saran wrap for their respective products. This generally happens only when a product is the best of its kind and has become the de-facto standard. This is certainly the case for Scotch Tape.It may cost a little more, but it generally worth it. Highly Recommended!",5,Its Scotch Tape! Highly Recommended!,1252022400,"09 4, 2009"
1084,A3OXHLG6DIBRW8,B00005C55O,"C. Hill ""CFH""","[0, 0]","This Mead Filler Paper is fairly standard, if just a little thinner than higher quality notebook paper. This is a decent deal as an add on product with free shipping.Recommended for casual writing needs.CFH",4,Notebook Paper - Recommended,1404604800,"07 6, 2014"
1171,A3OXHLG6DIBRW8,B00005MITU,"C. Hill ""CFH""","[0, 0]","The AT&T; Trimeline is a very basic corded phone that works when the power goes out. We bought three of these (one for our house, shop, and my mother's house) to use mostly as backup for when our various cordless phones become unusable in during power outages (more frequent than I like in our area).We have these connected to line splitters (Belkin RJ11 Plug/2-RJ11 Jack Modular T Adapter) and they work just fine. These also have physical switches to adjust the ringer volume and phone volume which, although limited, does give us some control. It is also handy that the keypad is ""backlit"" and draws power directly from the phone line, allowing you to see the numbers in the dark.While these phones do have the ability to store numbers and even speed-dial, we have not set them up to do it.Highly Recommended!CFH",5,Works Even When The Power Is Out - Highly Recommended,1284768000,"09 18, 2010"
...,...,...,...,...,...,...,...,...,...
50590,A3OXHLG6DIBRW8,B00FX51WJK,"C. Hill ""CFH""","[0, 1]","These Wilson Jones Ultra Duty View Binders are very good quality and are certainly a step up from the budget binders we usually pick up. I have seven of these binders in varying thickness and all of them are excellent choices for holding important presentations and documentation.This is marketed as having Extra Durable Hinges and they are indeed quite sturdy compared to the lower end binders we buy in bulk. These are more expensive, so would reserve these for customer use instead of causal office use.Recommended!CFH",4,Good Quality Binder - Recommended!,1405468800,"07 16, 2014"
50664,A3OXHLG6DIBRW8,B00FZ8ZRKU,"C. Hill ""CFH""","[0, 0]","These Wilson Jones Heavy Duty D-Ring View Binders with Extra Durable Hinges are very good quality and are certainly a step up from the budget binders we usually pick up. I have seven of these binders in varying thickness and all of them are excellent choices for holding important presentations and documentation.This is marketed as having Extra Durable Hinges and they are indeed quite sturdy compared to the lower end binders we buy in bulk. These are more expensive, so would reserve these for customer use instead of causal office use.Recommended!CFH",4,Good Quality Binder - Recommended,1405468800,"07 16, 2014"
51595,A3OXHLG6DIBRW8,B00GGBCRU8,"C. Hill ""CFH""","[1, 1]","This Monkey Fist Self Defense Keychain is seriously intimidating when transitioned into the hand but otherwise looks like a long keychain fob to the casual observer. We received these in Pink, Camo, Red/White/Blue, Black, Blue (this one), and Green and everyone in my family picked one for their keychain.Here are my observations:+ Construction; these are 550 Paracord weaved around a 1&#34; steel ball+ Quality; held up to some rigorous testing where my teen son used his to smash up some old ceramic molds (tough stuff)+ Size; big enough to be effective, small enough to easily carry in a pocketOverall, this can provide a a little peace of mind (practice with it first) and also works well as a keychain!Highly Recommended!CFHNote: Sample provided to review.",5,Looks Good and Functional As Well - Highly Recommended,1404000000,"06 29, 2014"
52691,A3OXHLG6DIBRW8,B00JAKXFQW,"C. Hill ""CFH""","[0, 0]","These Avery Textured Wraparound Labels are excellent quality and the 7.85&#34; x 1.75&#34; strips are conveniently sized for larger packages or bottles. While there are no templates for printing on these, I made my own using MS PowerPoint but any paint or presentation software will work fine.The material can also be handwritten on for a truly unique label. The labels will adhere to most surfaces, including glass, which makes them very versatile.Highly Recommended!CFH",5,Excellent For Custom Labels - Highly Recommended,1405814400,"07 20, 2014"
52833,A3OXHLG6DIBRW8,B00JIX4OTI,"C. Hill ""CFH""","[0, 0]","This Five Star Flex Hybrid NoteBinder is an excellent choice for the student that needs to carry different types of papers, such as note paper and handouts. The design is quite good, with plenty of room for standard notebook paper and also having pockets for pages without holes.The main issues I have with this are the plastic rings and cover that makes this feel like it is student oriented rather than an office grade product.Otherwise this is a very handy notebook/binder.Highly Recommended!CFH",5,Great For Students - Highly Recommended,1405468800,"07 16, 2014"

In [77]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime'],
      dtype='object')

In [78]:
df.rename(columns={'overall': 'rating','reviewText':'review','reviewTime':'time'}, inplace=True)

**helpful is Amazon's way of storing how many people found that review useful — it's stored as a pair of numbers: [helpful_votes, total_votes].**

In [79]:
df.head()

       reviewerID        asin         reviewerName helpful  \
0  A32T2H8150OJLU  B00000JBLH                  ARH  [3, 4]
1  A3MAFS04ZABRGO  B00000JBLH     Let it Be "Alan"  [7, 9]
2  A1F1A0QQP2XVH5  B00000JBLH               Mark B  [3, 3]
3   A49R5DBXXQDE5  B00000JBLH         R. D Johnson  [7, 8]
4  A2XRMQA6PJ5ZJ8  B00000JBLH  Roger J. Buffington  [0, 0]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        review  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling.  I searched for another one to replace it, but found one difficult to come by in my area.  So, I decided to buy up and purchased an HP 49G.  What a mistake!  I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best.  The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you.  It's programmable.  It does basic statistics well, and many business applications too.  The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend.  I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!
1  WHY THIS BELATED REVIEW? I feel very obliged to share my views about this old workhorse, the HP12C GOLD at its 25th anniversary and my 1Oth year as a satisfied ower user and fan. Especially after sharing my frank views on Amazon about two of its three successors on Amazon.com, burying the HP12c Platinum (2004 1st release, HP12cP) and praising the HP12c Platiunum Anniversary Edition (2006 3rd release, HP12cPAE or HP12cPA).To the majority of HP 12c calculator owners and fans, including the non-techkie nerd like myself, the name Hewlett-Packard To the majority of HP 12c calculator owners and fans. The brandname of Hewlett-Packard is synonymous with the highest quality and best range offered in handheld electronic business financial calculators before the first generation of personal computers hits the desktops of business users.To date (December 2007), the bearer of this "gold" standard is none other than the HP12C HP's "golden boy" in its calculator business segment.The HP12C now a matured product, is the only continuing HP handheld surviving calculator product since '81 and probably the longest selling electronic calculator ever. According to HP almost 15 million HP 12Cs, cPs was sold since ,it is probably the best selling HP (and RPN) calculator ever.As a proven product, the HP12C "gold" works from day 1, with its form factor and sofware remaining unchanged and has not been dethroned by rivals and even its HP successors which had come and go.Even with PC software versions being sold, the 12C remains the truly indispensable "portable" finance-business heldheld computer for its owners, professionals and students alike. This handy companion powers up immediately and is faster than any portable personal computers to jump right into the action.The HP12C is a serious product and the ultimate time tested solution, field tested proven by its users and survived all its rival products, the workhorse moves on.Anyone in charge of this HP line should always bear in mind that the continued production run of the HP 12c is a testimony of HP's quality and standard expected by its customers.Don't just listen to a HP12C fan here, I own and am using three out of 4 models of the HP 12C series, and it is amusing and somewhat disappointing to observe that it had taken HP at least four years and two major upgrades of the HP 12c Platinium, in its futile attempt to "fix & retire" the HP12C with three successors in the form of HP12cPlatinum since 2004.It would seems especially frustrating on the part of HP, to realize after all the effort spent on remaking the HP12cPlatinum models that it would not outdone its siblings the HP10bII and HP17bII+ series to seriously challenge the HP12C Gold.  However, by their own rights the HP10Bs and HP17Bs, and the HP12cPlatinum may find their rightful place in the HP financial calculator line, differentiating the HP12C GOLD in terms of price and functions.IMHO, this had happened because the following golden rules were infringed by HP...GOLDEN RULE I - A PRODUCT WHICH STILL SELLS ITSELF IS NEVER OBSOLETE.GOLDEN RULE II - IF IT AREN'T BROKEN, DON't FIX IT ! "The gold rule of thumb should always be guarded as gospel by the HP heldheld calculator product team. Based on the same reasoning, the HP12C's built quality and product standard is paramount to its users.GOLDEN RULE III - ALWAYS LISTEN TO YOUR CUSTOMERS! If in doubt, see rules I & II.GOLDEN RULE IV - ONLY OUTSOURCE THE MANUFACTURING OF YOUR PRODUCT TO SOMEONE WHO COULD BETTER YOUR OWN PRODUCT QUALITY. If in doubt ask IBM about Lenovo.GOLDEN RULE V - THE BENCHMARKING INDUSTRY STANDARD FOR THIS PRODUCT LINE IS THE HP12C. Just in case, if HP does not know or is not listening to its customers.GOLDEN RULE VI - DO NOT DISCONTINUE THE ICONIC HP12C GOLD. HP needs no reminder that the customer is always right. Please let your customer, the ultimate market force decide if the HP12C should ever be retired.As an ardent fan of HP12C and line of financial business & scientific calculators, I am of the view that the day when HP discontinue the HP12C would be the day it exit this business segment. I speculate this would happen when the HP brandname disappears from the 12C just like after IBM name had disappeared from ThinkPads and ThinkCentres.Since the price of GOLD is on the rise, it is indeed puzzling to fans of the HP12C, why HP did not release a genuine HP12C gold 25th anniversary model for the fans to mark the occasion, if replacing the discontinuing the HP12C GOLD is the intention READ ALL GOLDEN RULES above.To be fair, the silver HP12c Platinum Anniversary is very nice and has spotted the "retro" silver look of the HP 11C, however, it is still not the GOLD standard. With HP missing this golden opportunity to mark the occasion, I would love to see and own a HP 12C engraved with 50th Anniversary logo, reckon that this would be the ultimate testimony for the HP12C and a milestone for its fans.Looking forward, a GOLD 50th anniversary HP12C Anniversary model would be very nice for the fans.For HP, this is a lucrative business proposition. By now, they would have realized that if they have any of its products which could hit a 50th year home run  in 2031, it would not be from its other product line-it would be this original HP12C GOLD standard bearer. So please treat the old workhorse with the upmost respect!

In [80]:
df.dtypes

reviewerID        object
asin              object
reviewerName      object
helpful           object
review            object
rating             int64
summary           object
unixReviewTime     int64
time              object
dtype: object

In [81]:
df['new_time'] = pd.to_datetime(df['time'], format='%m %d, %Y')

In [82]:
pd.set_option('display.max_colwidth', None)   # show full text, no cutoff

In [86]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,review,rating,summary,unixReviewTime,time,new_time,review_date,review_year,review_month,review_day,day_of_week,is_weekend
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004",2004-09-03,2004-09-03,2004,9,3,Friday,False

In [87]:
df["review_date"] = pd.to_datetime(df["unixReviewTime"], unit="s")


df["review_year"] = df["review_date"].dt.year
df["review_month"] = df["review_date"].dt.month
df["review_day"] = df["review_date"].dt.day
df["day_of_week"] = df["review_date"].dt.day_name()
df["is_weekend"] = df["review_date"].dt.dayofweek >= 5

In [88]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,review,rating,summary,unixReviewTime,time,new_time,review_date,review_year,review_month,review_day,day_of_week,is_weekend
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004",2004-09-03,2004-09-03,2004,9,3,Friday,False

In [89]:
df["review_datetime"].head().dt.strftime("%Y-%m-%d %H:%M:%S")

KeyError: 'review_datetime'